# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version=0.3.0-beta.1
maven_group=io.github.tr100000
archives_base_name=trutils

# Dependencies
# https://fabricmc.net/develop/
minecraft_version=26.2-rc-2
loom_version=1.17-SNAPSHOT
loader_version=0.19.3

fabric_version=0.152.1+26.2
modmenu_version=20.0.0-alpha.1

modrinth_extra_minecraft_versions=
